name: release
on: [push]
jobs:
  realease:
    name: build;
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0
        
      - name: install nodejs
        uses: actions/setup-node@v3.0.0
        
      - name: install dependences
        run: npm install
      
      - name: release
        if: matrix.os == 'windows-latest'
        run: npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Upload File
        uses: actions/upload-artifact@v2
        with:
          # 上传后文件的名称
          name: windows
          # 打包的路径以及文件过滤，此为仅打包dist目录下的exe文件
          path: ./
